### ISSUE TITLE
Wrong file name for 0.0.5 release version

### ISSUE THREAD

**Issue by 0TshELn1ck** [madflow/trivy-plugin-notify#3]
`2024-11-22T11:16:52Z	FATAL	Fatal error	unable to run notify plugin: plugin exec: fork/exec /root/.trivy/plugins/notify/notify: no such file or directory`

ls -all /root/.trivy/plugins/notify/
total 7524
drwxr-xr-x 2 root root    4096 Nov 22 11:09 .
drwxr-xr-x 3 root root    4096 Nov 22 11:09 ..
-rw-r--r-- 1 root root   11357 Nov 21 07:57 LICENSE
-rw-r--r-- 1 root root    4732 Nov 21 07:57 README.md
-rwxr-xr-x 1 root root 7667864 Nov 21 07:58 count
-rw-r--r-- 1 root root    1148 Nov 22 11:09 plugin.yaml

`notify` file is absent for 0.0.5 release.

**Comment by madflow** [comment]
ooops... unforced error. Thank you for reporting this :)

I released 0.0.6 with the fix.

**Comment by 0TshELn1ck** [comment]
Thank you. 
Closed :)
