### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by 0TshELn1ck** [madflow/trivy-plugin-notify#7]
Hello. Is it possible to add functionality related to "Results" field?
if trivy `json.stdout.result` is empty - do not send a notification.
This will prevent a lot of noise. 

PS. Thanks for the GitHub env wrapper.

**Comment by madflow** [comment]
This sounds like a reasonable change and it should probably be the default behaviour. 👍 

Maybe it can be made possible to opt in via a `--sth` cli argument. I can take a stab at it.

**Comment by madflow** [comment]
I released a new version. Now, there has to be a "Results" key in the scan result as a default. 

It is possible to opt-in via `--send-always`.

All still rough around the edges. There should be some tests covering this.

This should reduce the noice for now ;)

**Comment by 0TshELn1ck** [comment]
Hello @madflow 
Cool. 
It works as expected. 
Thank you.
Tested, Closed :)

**Comment by madflow** [comment]
There seems to be more work, that has to be done. At least for `vuln` scanning. I only tested this with an "empty" directory with no dependencies. There can be "Results" - but no actual scanning results.

https://github.com/madflow/trivy-plugin-notify/issues/15
